/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as PagesNewRouteImport } from './routes/pages.new'
import { Route as BlogNewRouteImport } from './routes/blog.new'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'
import { Route as PagesPageIdEditRouteImport } from './routes/pages.$pageId.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SitesRoute,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => SitesRoute,
} as any)
const PagesNewRoute = PagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PagesRoute,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRoute,
} as any)
const PagesPageIdEditRoute = PagesPageIdEditRouteImport.update({
  id: '/$pageId/edit',
  path: '/$pageId/edit',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/pages': typeof PagesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/pages/new': typeof PagesNewRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/pages/$pageId/edit': typeof PagesPageIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/pages': typeof PagesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/pages/new': typeof PagesNewRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/pages/$pageId/edit': typeof PagesPageIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/pages': typeof PagesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/blog/new': typeof BlogNewRoute
  '/pages/new': typeof PagesNewRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/pages/$pageId/edit': typeof PagesPageIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/login'
    | '/media'
    | '/pages'
    | '/settings'
    | '/sites'
    | '/users'
    | '/blog/$postId'
    | '/blog/new'
    | '/pages/new'
    | '/sites/$siteId'
    | '/sites/new'
    | '/users/$userId'
    | '/users/new'
    | '/pages/$pageId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/login'
    | '/media'
    | '/pages'
    | '/settings'
    | '/sites'
    | '/users'
    | '/blog/$postId'
    | '/blog/new'
    | '/pages/new'
    | '/sites/$siteId'
    | '/sites/new'
    | '/users/$userId'
    | '/users/new'
    | '/pages/$pageId/edit'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/login'
    | '/media'
    | '/pages'
    | '/settings'
    | '/sites'
    | '/users'
    | '/blog/$postId'
    | '/blog/new'
    | '/pages/new'
    | '/sites/$siteId'
    | '/sites/new'
    | '/users/$userId'
    | '/users/new'
    | '/pages/$pageId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  PagesRoute: typeof PagesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof SitesRoute
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof SitesRoute
    }
    '/pages/new': {
      id: '/pages/new'
      path: '/new'
      fullPath: '/pages/new'
      preLoaderRoute: typeof PagesNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/pages/$pageId/edit': {
      id: '/pages/$pageId/edit'
      path: '/$pageId/edit'
      fullPath: '/pages/$pageId/edit'
      preLoaderRoute: typeof PagesPageIdEditRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogNewRoute: typeof BlogNewRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
  BlogNewRoute: BlogNewRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PagesRouteChildren {
  PagesNewRoute: typeof PagesNewRoute
  PagesPageIdEditRoute: typeof PagesPageIdEditRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesNewRoute: PagesNewRoute,
  PagesPageIdEditRoute: PagesPageIdEditRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface SitesRouteChildren {
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesNewRoute: typeof SitesNewRoute
}

const SitesRouteChildren: SitesRouteChildren = {
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesNewRoute: SitesNewRoute,
}

const SitesRouteWithChildren = SitesRoute._addFileChildren(SitesRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersNewRoute: typeof UsersNewRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersNewRoute: UsersNewRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  PagesRoute: PagesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
