type LiveManagementEditorCommandCategory =
  | 'history'
  | 'selection'
  | 'clipboard'
  | 'composition'
  | 'layer-state'
  | 'layer-order'
  | 'layout'
  | 'view'
  | 'shell'
  | 'workflow';

type LiveManagementEditorCommandScope =
  | 'canvas'
  | 'selected-layer'
  | 'selected-layers'
  | 'selected-sibling-scope'
  | 'selected-child-scope'
  | 'selected-container'
  | 'viewport'
  | 'shell'
  | 'document';

type LiveManagementEditorCommand = {
  id: string;
  label: string;
  category: LiveManagementEditorCommandCategory;
  targetScope: LiveManagementEditorCommandScope;
  testId: string;
  shortcut?: string;
  ariaKeyshortcuts?: string;
  minSelected?: number;
  sameParentRequired?: boolean;
  unlockedRequired?: boolean;
  editorGroupRequired?: boolean;
  sdkHelper?: string;
  apiHelper?: string;
  mutates?: string[];
  targetPaths?: string[];
  stateRule: string;
};

const command = (item: LiveManagementEditorCommand) => item;

export const liveManagementEditorCommandRegistry = {
  schemaVersion: 'backy.editor-command-registry.v1',
  source: 'live-management-discovery',
  generatedFrom: 'page-editor',
  stateModel: {
    runtimeState: 'computed-by-editor-client',
    stateValues: ['ready', 'disabled', 'hidden'],
    reasonField: 'reason',
    selectionFields: [
      'selectedIds',
      'selectedParentId',
      'selectedEntriesShareParent',
      'selectableSiblingIds',
      'selectableChildLayerIds',
    ],
    clipboardFields: ['clipboardElements', 'pasteTargetMode', 'pasteTargetLabel'],
    documentFields: ['canEdit', 'canPublish', 'isSaving', 'isPreview', 'hideSave', 'hideSettings'],
  },
  categories: [
    { id: 'history', label: 'History', commandIds: ['undo', 'redo'] },
    { id: 'clipboard', label: 'Clipboard', commandIds: ['copy-selection', 'cut-selection', 'paste-selection', 'duplicate-selection'] },
    { id: 'selection', label: 'Selection', commandIds: ['select-sibling-layers', 'select-child-layers', 'select-parent-layer', 'select-child-layer', 'delete-selection'] },
    { id: 'composition', label: 'Composition', commandIds: ['group-selection', 'ungroup-selection'] },
    { id: 'layer-state', label: 'Layer state', commandIds: ['toggle-selection-visibility', 'toggle-selection-lock'] },
    { id: 'layer-order', label: 'Layer order', commandIds: ['send-to-back', 'send-backward', 'bring-forward', 'bring-to-front'] },
    {
      id: 'layout',
      label: 'Layout',
      commandIds: [
        'align-left',
        'align-center',
        'align-right',
        'align-top',
        'align-middle',
        'align-bottom',
        'distribute-horizontal',
        'distribute-vertical',
      ],
    },
    { id: 'shell', label: 'Shell', commandIds: ['toggle-component-panel', 'toggle-layers-panel', 'toggle-inspector-panel', 'toggle-focus-mode'] },
    { id: 'view', label: 'View', commandIds: ['toggle-preview', 'toggle-grid', 'toggle-snap', 'toggle-pan', 'zoom-out', 'zoom-in', 'zoom-fit'] },
    { id: 'workflow', label: 'Workflow', commandIds: ['open-page-settings', 'reload-page', 'publish-page', 'save-page'] },
  ],
  commands: [
    command({
      id: 'undo',
      label: 'Undo',
      category: 'history',
      targetScope: 'canvas',
      shortcut: 'Cmd/Ctrl+Z',
      ariaKeyshortcuts: 'Control+Z Meta+Z',
      testId: 'editor-undo',
      stateRule: 'ready when historyIndex is greater than 0 and canvas mutations are enabled',
    }),
    command({
      id: 'redo',
      label: 'Redo',
      category: 'history',
      targetScope: 'canvas',
      shortcut: 'Cmd/Ctrl+Y or Shift+Cmd/Ctrl+Z',
      ariaKeyshortcuts: 'Control+Y Meta+Y Shift+Control+Z Shift+Meta+Z',
      testId: 'editor-redo',
      stateRule: 'ready when historyIndex is below the latest history entry and canvas mutations are enabled',
    }),
    command({
      id: 'copy-selection',
      label: 'Copy selected layers',
      category: 'clipboard',
      targetScope: 'selected-layers',
      shortcut: 'Cmd/Ctrl+C',
      ariaKeyshortcuts: 'Control+C Meta+C',
      testId: 'editor-copy-selection',
      minSelected: 1,
      sameParentRequired: true,
      stateRule: 'ready when one or more selected layers share a parent scope',
    }),
    command({
      id: 'cut-selection',
      label: 'Cut selected layers',
      category: 'clipboard',
      targetScope: 'selected-layers',
      shortcut: 'Cmd/Ctrl+X',
      ariaKeyshortcuts: 'Control+X Meta+X',
      testId: 'editor-cut-selection',
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      mutates: ['children', 'selection'],
      stateRule: 'ready when selected sibling layers are unlocked',
    }),
    command({
      id: 'paste-selection',
      label: 'Paste layers',
      category: 'clipboard',
      targetScope: 'selected-container',
      shortcut: 'Cmd/Ctrl+V',
      ariaKeyshortcuts: 'Control+V Meta+V',
      testId: 'editor-paste-selection',
      mutates: ['id', 'parentId', 'children', 'layout'],
      stateRule: 'ready when clipboardElements is not empty; target is selected container when compatible, otherwise canvas root',
    }),
    command({
      id: 'duplicate-selection',
      label: 'Duplicate selected layers',
      category: 'clipboard',
      targetScope: 'selected-layers',
      shortcut: 'Cmd/Ctrl+D',
      ariaKeyshortcuts: 'Control+D Meta+D',
      testId: 'editor-duplicate-selection',
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'duplicateBackyContentElement',
      mutates: ['id', 'parentId', 'children', 'layout'],
      stateRule: 'ready when selected sibling layers are unlocked',
    }),
    command({
      id: 'select-sibling-layers',
      label: 'Select sibling layers',
      category: 'selection',
      targetScope: 'selected-sibling-scope',
      shortcut: 'Cmd/Ctrl+A',
      ariaKeyshortcuts: 'Control+A Meta+A',
      testId: 'editor-select-sibling-layers',
      minSelected: 1,
      stateRule: 'ready when the selected layer has at least one visible unlocked sibling',
    }),
    command({
      id: 'select-child-layers',
      label: 'Select child layers',
      category: 'selection',
      targetScope: 'selected-child-scope',
      shortcut: 'Shift+Cmd/Ctrl+A',
      ariaKeyshortcuts: 'Shift+Control+A Shift+Meta+A',
      testId: 'editor-select-child-layers',
      minSelected: 1,
      stateRule: 'ready when selected layer has visible unlocked child layers',
    }),
    command({
      id: 'select-parent-layer',
      label: 'Select parent layer',
      category: 'selection',
      targetScope: 'selected-layer',
      shortcut: 'Shift+Enter',
      ariaKeyshortcuts: 'Shift+Enter',
      testId: 'editor-select-parent-layer',
      minSelected: 1,
      stateRule: 'ready when the active selection has a parentId',
    }),
    command({
      id: 'select-child-layer',
      label: 'Select first child layer',
      category: 'selection',
      targetScope: 'selected-child-scope',
      shortcut: 'Enter',
      ariaKeyshortcuts: 'Enter',
      testId: 'editor-select-child-layer',
      minSelected: 1,
      stateRule: 'ready when the selected layer has at least one visible unlocked child',
    }),
    command({
      id: 'group-selection',
      label: 'Group selected sibling layers',
      category: 'composition',
      targetScope: 'selected-sibling-scope',
      shortcut: 'Cmd/Ctrl+G',
      ariaKeyshortcuts: 'Control+G Meta+G',
      testId: 'editor-group-selection',
      minSelected: 2,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'groupBackyContentElements',
      mutates: ['props.editorGroup', 'children', 'parentId', 'responsive.tablet', 'responsive.mobile'],
      stateRule: 'ready when at least two selected layers are unlocked siblings',
    }),
    command({
      id: 'ungroup-selection',
      label: 'Ungroup selected editor groups',
      category: 'composition',
      targetScope: 'selected-sibling-scope',
      shortcut: 'Shift+Cmd/Ctrl+G',
      ariaKeyshortcuts: 'Shift+Control+G Shift+Meta+G',
      testId: 'editor-ungroup-selection',
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      editorGroupRequired: true,
      sdkHelper: 'ungroupBackyContentElements',
      mutates: ['children', 'parentId', 'responsive.tablet', 'responsive.mobile'],
      stateRule: 'ready when selected layers are unlocked editor groups in the same parent scope',
    }),
    command({
      id: 'toggle-selection-visibility',
      label: 'Toggle selected layer visibility',
      category: 'layer-state',
      targetScope: 'selected-layers',
      testId: 'editor-toggle-selection-visibility',
      minSelected: 1,
      unlockedRequired: true,
      sdkHelper: 'patchBackyContentElements',
      targetPaths: ['visible', 'responsive.tablet.visible', 'responsive.mobile.visible'],
      mutates: ['visible'],
      stateRule: 'ready when selected layers are not locked',
    }),
    command({
      id: 'toggle-selection-lock',
      label: 'Toggle selected layer lock',
      category: 'layer-state',
      targetScope: 'selected-layers',
      testId: 'editor-toggle-selection-lock',
      minSelected: 1,
      sdkHelper: 'patchBackyContentElements',
      targetPaths: ['locked', 'responsive.tablet.locked', 'responsive.mobile.locked'],
      mutates: ['locked'],
      stateRule: 'ready when at least one layer is selected',
    }),
    ...([
      ['send-to-back', 'Send to back', 'Shift+Cmd/Ctrl+[', 'Shift+Control+[ Shift+Meta+[', 'editor-send-to-back'],
      ['send-backward', 'Send backward', 'Cmd/Ctrl+[', 'Control+[ Meta+[', 'editor-send-backward'],
      ['bring-forward', 'Bring forward', 'Cmd/Ctrl+]', 'Control+] Meta+]', 'editor-bring-forward'],
      ['bring-to-front', 'Bring to front', 'Shift+Cmd/Ctrl+]', 'Shift+Control+] Shift+Meta+]', 'editor-bring-to-front'],
    ] as const).map(([id, label, shortcut, ariaKeyshortcuts, testId]) => command({
      id,
      label,
      category: 'layer-order',
      targetScope: 'selected-layers',
      shortcut,
      ariaKeyshortcuts,
      testId,
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'transformBackyContentElements',
      targetPaths: ['zIndex'],
      mutates: ['zIndex'],
      stateRule: 'ready when selected unlocked sibling layers have neighboring layers in the active scope',
    })),
    ...([
      ['align-left', 'Align left', 'editor-align-left'],
      ['align-center', 'Align horizontal center', 'editor-align-center'],
      ['align-right', 'Align right', 'editor-align-right'],
      ['align-top', 'Align top', 'editor-align-top'],
      ['align-middle', 'Align vertical center', 'editor-align-middle'],
      ['align-bottom', 'Align bottom', 'editor-align-bottom'],
    ] as const).map(([id, label, testId]) => command({
      id,
      label,
      category: 'layout',
      targetScope: 'selected-layers',
      testId,
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'transformBackyContentElements',
      targetPaths: ['x', 'y', 'responsive.tablet.x', 'responsive.tablet.y', 'responsive.mobile.x', 'responsive.mobile.y'],
      mutates: ['layout', 'responsive.tablet', 'responsive.mobile'],
      stateRule: 'ready when selected layers are visible unlocked siblings',
    })),
    command({
      id: 'distribute-horizontal',
      label: 'Distribute horizontal spacing',
      category: 'layout',
      targetScope: 'selected-layers',
      testId: 'editor-distribute-horizontal',
      minSelected: 3,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'transformBackyContentElements',
      targetPaths: ['x', 'responsive.tablet.x', 'responsive.mobile.x'],
      mutates: ['layout.x', 'responsive.tablet.x', 'responsive.mobile.x'],
      stateRule: 'ready when at least three visible unlocked sibling layers are selected',
    }),
    command({
      id: 'distribute-vertical',
      label: 'Distribute vertical spacing',
      category: 'layout',
      targetScope: 'selected-layers',
      testId: 'editor-distribute-vertical',
      minSelected: 3,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'transformBackyContentElements',
      targetPaths: ['y', 'responsive.tablet.y', 'responsive.mobile.y'],
      mutates: ['layout.y', 'responsive.tablet.y', 'responsive.mobile.y'],
      stateRule: 'ready when at least three visible unlocked sibling layers are selected',
    }),
    command({
      id: 'delete-selection',
      label: 'Delete selected layers',
      category: 'selection',
      targetScope: 'selected-layers',
      shortcut: 'Delete/Backspace',
      ariaKeyshortcuts: 'Delete Backspace',
      testId: 'editor-delete-selection',
      minSelected: 1,
      sameParentRequired: true,
      unlockedRequired: true,
      sdkHelper: 'deleteBackyContentElements',
      mutates: ['children'],
      stateRule: 'ready when selected sibling layers are unlocked',
    }),
    command({
      id: 'toggle-component-panel',
      label: 'Toggle components panel',
      category: 'shell',
      targetScope: 'shell',
      shortcut: 'B',
      ariaKeyshortcuts: 'B',
      testId: 'editor-toggle-component-panel',
      stateRule: 'ready in editable shell mode',
    }),
    command({
      id: 'toggle-layers-panel',
      label: 'Toggle layers panel',
      category: 'shell',
      targetScope: 'shell',
      shortcut: 'L',
      ariaKeyshortcuts: 'L',
      testId: 'editor-toggle-layers-panel',
      stateRule: 'ready in editable shell mode; exits focus mode when needed',
    }),
    command({
      id: 'toggle-inspector-panel',
      label: 'Toggle inspector panel',
      category: 'shell',
      targetScope: 'shell',
      shortcut: 'I',
      ariaKeyshortcuts: 'I',
      testId: 'editor-toggle-inspector-panel',
      stateRule: 'ready in editable shell mode; exits focus mode when needed',
    }),
    command({
      id: 'toggle-focus-mode',
      label: 'Toggle canvas focus mode',
      category: 'shell',
      targetScope: 'shell',
      shortcut: 'F',
      ariaKeyshortcuts: 'F',
      testId: 'editor-toggle-focus-mode',
      stateRule: 'ready in editor shell mode',
    }),
    command({
      id: 'toggle-preview',
      label: 'Toggle preview mode',
      category: 'view',
      targetScope: 'canvas',
      testId: 'editor-preview-toggle',
      stateRule: 'ready when the editor is not saving',
    }),
    command({
      id: 'toggle-grid',
      label: 'Toggle grid visibility',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'G',
      ariaKeyshortcuts: 'G',
      testId: 'editor-grid-visibility-toggle',
      stateRule: 'ready outside preview mode',
    }),
    command({
      id: 'toggle-snap',
      label: 'Toggle snapping',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'S',
      ariaKeyshortcuts: 'S',
      testId: 'editor-snap-toggle',
      stateRule: 'ready outside preview mode',
    }),
    command({
      id: 'toggle-pan',
      label: 'Toggle pan navigation',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'H or Space',
      ariaKeyshortcuts: 'H Space',
      testId: 'editor-pan-toggle',
      stateRule: 'ready outside preview mode; Space may be temporary pan',
    }),
    command({
      id: 'zoom-out',
      label: 'Zoom out',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'Cmd/Ctrl+-',
      ariaKeyshortcuts: 'Control+- Meta+-',
      testId: 'editor-zoom-out',
      stateRule: 'ready outside preview mode',
    }),
    command({
      id: 'zoom-in',
      label: 'Zoom in',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'Cmd/Ctrl+=',
      ariaKeyshortcuts: 'Control+= Meta+=',
      testId: 'editor-zoom-in',
      stateRule: 'ready outside preview mode',
    }),
    command({
      id: 'zoom-fit',
      label: 'Fit canvas',
      category: 'view',
      targetScope: 'viewport',
      shortcut: 'Cmd/Ctrl+0',
      ariaKeyshortcuts: 'Control+0 Meta+0',
      testId: 'editor-zoom-fit',
      stateRule: 'ready outside preview mode',
    }),
    command({
      id: 'open-page-settings',
      label: 'Open page or post settings',
      category: 'workflow',
      targetScope: 'document',
      testId: 'editor-page-settings',
      stateRule: 'ready when settings controls are visible and the editor is not saving',
    }),
    command({
      id: 'reload-page',
      label: 'Reload page or post',
      category: 'workflow',
      targetScope: 'document',
      testId: 'editor-reload-page',
      stateRule: 'ready when the editor is not saving',
    }),
    command({
      id: 'publish-page',
      label: 'Publish or unpublish page',
      category: 'workflow',
      targetScope: 'document',
      testId: 'editor-publish-page',
      apiHelper: 'publishAdminPage',
      stateRule: 'ready for page editors when canPublish is true and readiness gates allow publication; hidden for embedded non-page editors',
    }),
    command({
      id: 'save-page',
      label: 'Save page, post, or section',
      category: 'workflow',
      targetScope: 'document',
      shortcut: 'Ctrl+S',
      testId: 'editor-save-page',
      apiHelper: 'updateAdminPage or updateAdminBlogPost',
      stateRule: 'ready when save controls are visible, the editor is not saving, and canEdit is true',
    }),
  ],
  privacy: {
    includesSecretValues: false,
    includesAdminSessionValues: false,
    endpointTemplatesOnly: true,
  },
} as const;

export type LiveManagementEditorCommandRegistry = typeof liveManagementEditorCommandRegistry;
